### ISSUE TITLE
3.0 Roadmap

### ISSUE THREAD

**Issue by VamOSGS** [VamOSGS/react-preloaders#9]
3.0 Roadmap
- [x] Rewirte with react hooks.
- [x] Integrate testing system (Jest).
- [x] Integrate CI system (Travic CI).
- [x] Integrate prop-types.
- [x] Integrate styled-components.
- [x] Add custom preloaders possibility https://github.com/VamOSGS/react-preloaders/issues/4
- [x] Add manually stop loading functionalty https://github.com/VamOSGS/react-preloaders/issues/5
- [x] Create withPreloader function for extracting Preloaders with less code.
- [x] Add choice for closing transition (or custom transitions).
- [x] Add blur background.
- [x] Update library build.
- [x] Update (or rewrite) documentation.
- [x] Create examples
  - [x] Simple
  - [x] Manually stop loading
  - [ ] With custom loader component
- [x] Create repo card
- [x] Add new preloaders

Check 3.0 development progress in [development branch](https://github.com/VamOSGS/react-preloaders/tree/development).

**Comment by VamOSGS** [comment]
[react-preloaders v3.x.x](https://www.npmjs.com/package/react-preloaders) realized
